Auth
DenysMaksymKachalup/spring-bookstore pull request #10
Opened 2023-12-29 19:24 UTC by DenysMaksymKachalup

2023-12-29 19:44 UTC, sokimaaa commented on src/main/java/com/example/springonlinebookstore/controller/AuthenticationController.java
> +            throws RegistrationException {
```suggestion
    public UserDto register(@RequestBody
                                @Valid UserRegistrationRequestDto userRegistrationRequestDto)
            {
```

2023-12-29 19:44 UTC, sokimaaa commented on src/main/java/com/example/springonlinebookstore/controller/BookController.java
> +    public List<BookDto> search(@RequestBody BookSearchParameters bookSearchParameters,
Why remove valid? 
```suggestion
    public List<BookDto> search(@RequestBody @Valid BookSearchParameters bookSearchParameters,
```

2023-12-29 19:46 UTC, sokimaaa commented on src/main/java/com/example/springonlinebookstore/dto/user/UserRegistrationRequestDto.java
> +                message = "The password fields must match")})
Why so complicate usage of annotation? make something like this:
```suggestion
@FieldsValueMatch(
        field = "password",
                fieldMatch = "repeatPassword",
                message = "The password fields must match")
                )
```

2023-12-29 19:47 UTC, sokimaaa commented on src/main/java/com/example/springonlinebookstore/exception/RegistrationException.java
> +public class RegistrationException extends Exception {
make it unchecked exception

2023-12-29 19:47 UTC, sokimaaa commented on src/main/java/com/example/springonlinebookstore/model/User.java
> +@ToString
```suggestion
```

2023-12-29 19:48 UTC, sokimaaa commented on src/main/java/com/example/springonlinebookstore/service/UserService.java
> +            throws RegistrationException;
```suggestion
```

2023-12-29 19:48 UTC, sokimaaa commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/02-create-user-table.yml
consider adding `03-insert-users`

2023-12-30 11:32 UTC, Sanderfuck requested changes

2023-12-30 11:32 UTC, Sanderfuck commented on src/main/java/com/example/springonlinebookstore/dto/user/UserRegistrationRequestDto.java
> +
```suggestion
```

2023-12-30 11:32 UTC, Sanderfuck commented on src/main/java/com/example/springonlinebookstore/model/User.java
> +
```suggestion
```

2023-12-30 11:32 UTC, Sanderfuck commented on src/main/java/com/example/springonlinebookstore/model/User.java
> +
```suggestion
```

2023-12-30 11:32 UTC, Sanderfuck commented on src/main/java/com/example/springonlinebookstore/model/User.java
> +
```suggestion
```

2023-12-30 11:32 UTC, Sanderfuck commented on src/main/java/com/example/springonlinebookstore/annotation/FieldsValueMatch.java
> +
```suggestion
```

2024-01-03 14:27 UTC, merged